# Generated by Django 2.1 on 2018-09-28 20:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0008_post_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='CircleEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circle', models.CharField(choices=[('a', 'alpha'), ('b', 'bravo'), ('c', 'charlie'), ('d', 'delta'), ('e', 'echo'), ('f', 'foxtrot'), ('g', 'golf'), ('h', 'hotel'), ('i', 'india'), ('j', 'juliett')], default='a', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField()),
                ('receiver', models.ForeignKey(on_delete='cascade', related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete='cascade', related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.ForeignKey(on_delete='cascade', to='friends.Contact')),
                ('post', models.ForeignKey(on_delete='cascade', to='posts.Post')),
            ],
        ),
        migrations.AddField(
            model_name='circleentry',
            name='contact',
            field=models.ForeignKey(on_delete='cascade', to='friends.Contact'),
        ),
    ]
