# Generated by Django 2.1 on 2018-10-05 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_auto_20181005_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circleentry',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friends.Contact'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contact',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postcontact',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friends.Contact'),
        ),
        migrations.AlterField(
            model_name='postcontact',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
        ),
    ]
