# Generated by Django 2.1 on 2018-09-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RSSEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('author', models.CharField(max_length=200)),
                ('published', models.DateTimeField()),
                ('summary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RSSFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.URLField()),
                ('etag', models.CharField(max_length=50)),
                ('modified', models.CharField(max_length=50)),
            ],
        ),
    ]
