# Generated by Django 2.1 on 2018-09-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssfeed',
            name='etag',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rssfeed',
            name='modified',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
