# Generated by Django 2.1 on 2018-09-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_auto_20180924_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssfeed',
            name='etag',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rssfeed',
            name='modified',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
    ]
