# Generated by Django 2.1 on 2018-09-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_auto_20180924_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssentry',
            name='feed',
            field=models.ForeignKey(default='', on_delete='cascade', to='feeds.RSSFeed'),
            preserve_default=False,
        ),
    ]
