# Generated by Django 2.1 on 2018-09-24 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0006_auto_20180924_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssfeed',
            name='title',
            field=models.CharField(default='NYTimes Homepage', max_length=100),
            preserve_default=False,
        ),
    ]
