# Generated by Django 2.1 on 2018-09-30 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0007_rssfeed_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rssentry',
            name='author',
        ),
    ]
