# Generated by Django 2.1 on 2018-10-05 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0008_remove_rssentry_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssentry',
            name='feed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feeds.RSSFeed'),
        ),
    ]
