# Generated by Django 2.1 on 2018-08-31 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parentcomment',
            field=models.ForeignKey(blank=True, default='', on_delete='cascade', to='posts.Comment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default='', on_delete='cascade', to='posts.Post'),
            preserve_default=False,
        ),
    ]
