# Generated by Django 2.1 on 2018-08-31 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20180831_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parentcomment',
            field=models.ForeignKey(blank=True, null=True, on_delete='cascade', to='posts.Comment'),
        ),
    ]
