# Generated by Django 2.1 on 2018-09-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20180831_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='example-url'),
            preserve_default=False,
        ),
    ]
